server:
  port: 8084

logos:
  db:
    host: 127.0.0.1
    database: logos-article
    user: root
    password: 123
  swagger:
    title: "文章服务接口文档"
    desc: "文章服务接口文档"
    package: com.violet.article.controller