server:
  port: 8085

spring:
  redis:
    host: localhost
    port: 6379

logos:
  db:
    host: 127.0.0.1
    database: logos-comment
    user: root
    password: 123
  swagger:
    title: "评论服务接口文档"
    desc: "评论服务接口文档"
    package: com.violet.comment.controller